server {
    listen 8080 default_server;
    listen [::]:8080 default_server;

    root /app/static;
    index index.seo.html index.html;
    charset utf-8;

    location /ws/ {
        proxy_pass http://127.0.0.1:8082/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8082/api/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
